CREATE TABLE clients (
    client_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    signup_date DATE NOT NULL,
    state_code CHAR(2),
    phone_number VARCHAR2(20),
    CONSTRAINT chk_clients_state CHECK (state_code IS NULL OR LENGTH(state_code) = 2)
);

CREATE TABLE paneltypes (
    panel_type_code VARCHAR2(10) PRIMARY KEY,
    description VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE projects (
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id NUMBER NOT NULL,
    project_name VARCHAR2(100) NOT NULL,
    panel_count NUMBER NOT NULL,
    expected_kw NUMBER(5,2),
    install_date DATE NOT NULL,
    inspection_date DATE,
    status VARCHAR2(20),
    CONSTRAINT uq_projects_client_name UNIQUE (client_id, project_name),
    CONSTRAINT chk_projects_panel_count CHECK (panel_count > 0),
    CONSTRAINT chk_projects_status CHECK (status IN ('Planned', 'Installed', 'Inspected', 'Cancelled')),
    CONSTRAINT fk_projects_client FOREIGN KEY (client_id)
        REFERENCES clients(client_id)
);

CREATE TABLE panels (
    panel_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id NUMBER NOT NULL,
    panel_type_code VARCHAR2(10) NOT NULL,
    capacity_kw NUMBER(4,2),
    serial_number VARCHAR2(50) NOT NULL UNIQUE,
    CONSTRAINT chk_panels_capacity CHECK (capacity_kw > 0),
    CONSTRAINT fk_panels_project FOREIGN KEY (project_id)
        REFERENCES projects(project_id) ON DELETE CASCADE,
    CONSTRAINT fk_panels_type FOREIGN KEY (panel_type_code)
        REFERENCES paneltypes(panel_type_code)
);

CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id NUMBER NOT NULL,
    amount NUMBER(8,2) NOT NULL,
    payment_date DATE NOT NULL,
    payment_method VARCHAR2(20),
    note VARCHAR2(200),
    CONSTRAINT chk_payments_amount CHECK (amount > 0),
    CONSTRAINT chk_payments_method CHECK (payment_method IN ('Credit', 'ACH', 'Check')),
    CONSTRAINT fk_payments_project FOREIGN KEY (project_id)
        REFERENCES projects(project_id) ON DELETE CASCADE
);
